apiVersion: v2
name: jellyfin
description: A Helm chart for Jellyfin Media Server
type: application
home: https://jellyfin.org/
icon: https://jellyfin.org/images/logo.svg
keywords:
  - jellyfin
  - media
  - self-hosted
version: 2.6.0
appVersion: 10.11.2
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add envFrom support to load environment variables from ConfigMap or Secret
    - kind: added
      description: Add revisionHistoryLimit parameter to control rollback history retention (defaults to 3 instead of Kubernetes default 10)
